//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gambit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Kontakt = new HashSet<Kontakt>();
        }
    
        public string miejscowosc { get; set; }
        public Nullable<int> nrDomu { get; set; }
        public Nullable<int> nrLokalu { get; set; }
        public string kodPocztowy { get; set; }
        public string wojewodztwo { get; set; }
        public string kraj { get; set; }
        public int addressId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontakt> Kontakt { get; set; }
    }
}
