//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gambit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kontakt()
        {
            this.AspNetUsers = new HashSet<AspNetUsers>();
        }
    
        public int kontaktId { get; set; }
        public Nullable<int> addressId { get; set; }
        public Nullable<int> infoId { get; set; }
        public string numer { get; set; }
        public string kontaktEmail { get; set; }
        public string imie { get; set; }
        public string imie2 { get; set; }
        public string nazwisko { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Email Email { get; set; }
        public virtual Info Info { get; set; }
        public virtual Telefon Telefon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
    }
}
